name: task

on:
  workflow_dispatch:
  schedule:
  - cron: '5 5,11,17,23 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install pandas requests
      - run: python task.py
